# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/storage/Documents/Programming/C++/MonoCAM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/storage/Documents/Programming/C++/MonoCAM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/storage/Documents/Programming/C++/MonoCAM/CMakeFiles /media/storage/Documents/Programming/C++/MonoCAM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/storage/Documents/Programming/C++/MonoCAM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MonoCAM

# Build rule for target.
MonoCAM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MonoCAM
.PHONY : MonoCAM

# fast build rule for target.
MonoCAM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/build
.PHONY : MonoCAM/fast

mono_cap.o: mono_cap.cc.o
.PHONY : mono_cap.o

# target to build an object file
mono_cap.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/mono_cap.cc.o
.PHONY : mono_cap.cc.o

mono_cap.i: mono_cap.cc.i
.PHONY : mono_cap.i

# target to preprocess a source file
mono_cap.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/mono_cap.cc.i
.PHONY : mono_cap.cc.i

mono_cap.s: mono_cap.cc.s
.PHONY : mono_cap.s

# target to generate assembly for a file
mono_cap.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/mono_cap.cc.s
.PHONY : mono_cap.cc.s

monocam.o: monocam.cpp.o
.PHONY : monocam.o

# target to build an object file
monocam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/monocam.cpp.o
.PHONY : monocam.cpp.o

monocam.i: monocam.cpp.i
.PHONY : monocam.i

# target to preprocess a source file
monocam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/monocam.cpp.i
.PHONY : monocam.cpp.i

monocam.s: monocam.cpp.s
.PHONY : monocam.s

# target to generate assembly for a file
monocam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/monocam.cpp.s
.PHONY : monocam.cpp.s

monocam_ux.o: monocam_ux.cc.o
.PHONY : monocam_ux.o

# target to build an object file
monocam_ux.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/monocam_ux.cc.o
.PHONY : monocam_ux.cc.o

monocam_ux.i: monocam_ux.cc.i
.PHONY : monocam_ux.i

# target to preprocess a source file
monocam_ux.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/monocam_ux.cc.i
.PHONY : monocam_ux.cc.i

monocam_ux.s: monocam_ux.cc.s
.PHONY : monocam_ux.s

# target to generate assembly for a file
monocam_ux.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MonoCAM.dir/build.make CMakeFiles/MonoCAM.dir/monocam_ux.cc.s
.PHONY : monocam_ux.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MonoCAM"
	@echo "... mono_cap.o"
	@echo "... mono_cap.i"
	@echo "... mono_cap.s"
	@echo "... monocam.o"
	@echo "... monocam.i"
	@echo "... monocam.s"
	@echo "... monocam_ux.o"
	@echo "... monocam_ux.i"
	@echo "... monocam_ux.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

